version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bst-mysql
    environment:
      MYSQL_DATABASE: bstdb
      MYSQL_USER: bstuser
      MYSQL_PASSWORD: bstpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"         # <-- host:container
    # You don't need to force the auth plugin; the driver supports the default.
    # command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bst-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: bstuser
      PMA_PASSWORD: bstpass
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
